### ISSUE TITLE
linux/amd64 image not building correctly

### ISSUE THREAD

**Issue by timetinytim** [damomurf/coredns-tailscale#73]
While the github workflow definitely seems to be set up to build one, the two architectures built for the docker images are `linux/arm64` and `unknown/unknown`.

**Comment by timetinytim** [comment]
After doing some reading, this seems to be a known issue with `build-push-action@v5` as discussed here: https://github.com/docker/build-push-action/issues/820

The fix seems as simple as just disabling provenance attestations for the docker build.

**Comment by damomurf** [comment]
@timetinytim Thanks for the fix, I’ve just pushed  v0.3.5 which includes it: https://github.com/damomurf/coredns-tailscale/releases/tag/v0.3.5.
